name: paddle
channels:
- pytorch
- conda-forge
dependencies:
- python
- cudatoolkit=11.0
- pytorch
- pytorch-lightning
- torchvision
- albumentations
- pillow # TODO: test pillow-simd, channel: zegami
- skimage
- cython
- seaborn
- matplotlib
- pyyaml
- tqdm
- setuptools
- omegaconf
- pandas
- scipy
- numpy
- fire
- pip
- pip:
    - diplib
    - opencv-python
    - hydra-core==1.1.0.dev3