name: mrcnn_pytorch
channels:
- pytorch
- defaults
- conda-forge
dependencies:
- pytorch
- torchvision
- cudatoolkit=10.1
- ignite
- tensorboard
- tensorboardx
- matplotlib
- pandas
- seaborn
- tqdm
- scikit-image
- cython
- pip
- pip:
  - git+https://github.com/maxfrei750/cocoapi.git#subdirectory=PythonAPI
#  - git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
#  - git+https://github.com/waleedka/coco.git#subdirectory=PythonAPI  # for linux
