name: MaskRCNN
channels:
- pytorch
- defaults
- conda-forge
dependencies:
- python>=3.8
- pytorch
- torchvision
- cudatoolkit=11.0
- ignite
- pytorch-lightning
- tensorboard
- tensorboardx
- matplotlib
- pandas
- seaborn
- tqdm
- scikit-image
- cython
- pycocotools
- albumentations
- fire
- hydra-core
- pip
- pip:
    - diplib
    - opencv-python
    - git+https://github.com/omry/omegaconf.git@master
#  - git+https://github.com/gautamchitnis/cocoapi.git@cocodataset-master#subdirectory=PythonAPI # for Windows
