name: MaskRCNN
channels:
- pytorch
- defaults
- conda-forge
dependencies:
- pytorch
- torchvision
- cudatoolkit=10.1
- ignite
- tensorboard
- tensorboardx
- matplotlib
- pandas
- seaborn
- tqdm
- scikit-image
- cython
- pycocotools
- albumentations
- opencv
- fire
#- pip
#- pip:
#  - git+https://github.com/gautamchitnis/cocoapi.git@cocodataset-master#subdirectory=PythonAPI # for Windows
