name: MaskRCNN
channels:
- pytorch
- defaults
- conda-forge
dependencies:
- python>=3.8
- pytorch
- torchvision
- cudatoolkit=10.1
- ignite
- pytorch-lightning
- tensorboard
- tensorboardx
- matplotlib
- pandas
- seaborn
- tqdm
- scikit-image
- cython
- pycocotools
- albumentations
- opencv
- fire
- pip
- pip:
    - diplib
#  - git+https://github.com/gautamchitnis/cocoapi.git@cocodataset-master#subdirectory=PythonAPI # for Windows
