name: mrcnn_pytorch
channels:
- defaults
- pytorch
- conda-forge
dependencies:
- pytorch
- torchvision
- cudatoolkit=10.1
- ignite
- tensorboard
- tensorboardx
- matplotlib
- pandas
- seaborn
- tqdm
- scikit-image
- pip
- pip:
  - pycocotools
