model_name: krcnn
n_classes: 2  # Background and Fiber
n_keypoints: 20
batch_size_train: 2
batch_size_val: 1
max_epochs: 10
random_seed: 12345
print_frequency: 10
subset_train: training
subset_val: validation