general:
  random_seed: 42
model:
  n_classes: 2  # Background and Particle
data:
  root_folder: "data"
  class_names:
    1: particle
  batch_size_training: 2
  batch_size_validation: 1
  n_data_loader_workers: 4
  subset_training: training
  subset_validation: validation
training:
  max_epochs: 100
logging:
  root_folder: "logs"
  print_frequency: 10
optimizer:
  name: sgd
  parameters:
    lr: 0.005
    momentum: 0.9
    weight_decay: 0.0005
lr_scheduler:
  step_size: 10
  gamma: 0.1
