general:
  random_seed: 12345
model:
  name: mrcnn
  n_classes: 2  # Background and Fiber
data:
  class_names:
    1: fiber
  batch_size_train: 2
  batch_size_val: 1
  n_data_loader_workers: 4
  subset_train: training
  subset_val: validation
training:
  max_epochs: 10
logging:
  print_frequency: 10
optimizer:
  name: sgd
  parameters:
    lr: 0.005
    momentum: 0.9
    weight_decay: 0.0005
lr_scheduler:
  step_size: 3
  gamma: 0.1
